---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "nanopore-transcriptome-analyze"
# Repository URL:
repo: "https://github.com/martynakgajos/nanopore-transcriptome-analysis"

## Pipeline-specific parameters

# Input genome:
genome_fasta: "GRCh38.p12.primary_assembly.genome.fa"
genome_annot: "gencode.v29.annotation.gtf"
# genome_fasta and genome_annot must be a filename corresponding to file that has been placed in the ReferenceData folder

# samples with .fastq extenssion must be placed in the RawData folder
samples:
    OJ32: "day_5"
    OJ33: "day_0"
    OJ34: "day_3"

threads: 16

pychopper: TRUE

# Use annotation to improve splice junction mapping (minimap2 --junc_bed parameter)
minimap2_opts_junction: TRUE

# Minimum read quality to keep:
min_mean_q: 5

# Stringency of porechop heuristic:
porechop_heu_stringency: 0.25

# Options passed to minimap2 during indexing:
minimap_index_opts: "-k14"

# Extra options passed to minimap2:
minimap2_opts: "-uf"  # required for stranded data e.g. when pychopper filtered

# Minmum mapping quality:
minimum_mapping_quality: 10

# Options passed to spliced_bam2gff:
spliced_bam2gff_opts: "-s"  # required for stranded data e.g. when pychopper filtered

# -c parameter:
minimum_cluster_size: 3

# -p parameter:
minimum_isoform_percent: 0.0

# -d parameter:
exon_boundary_tolerance: 10

# -e parameter:
terminal_exon_boundary_tolerance: 50

# Extra options passed to minimap2 when mapping polished reads:
minimap2_opts_polished: "-uf"   # required for stranded data e.g. when pychopper filtered

# Options passed to spliced_bam2gff when converting alignments of polished reads:
spliced_bam2gff_opts_pol: "-s"  # required for stranded data e.g. when pychopper filtered

# Options passed to collapse_partials when collapsing fragmentation artifacts
# Internal exon boundary tolerance:
collapse_internal_tol: 5

# Five prime boundary tolerance:
collapse_five_tol: 500

# Three prime boundary tolerance:
collapse_three_tol: 50
